services:
  - type: web
    name: hrms-lite-backend
    env: python
    runtime: python-3.11.7
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: MONGODB_URL
        sync: false
